name: "aimm"

services:
    postgres:
        image: postgres:latest
        # restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_ROOT_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432

    mongo:
        image: mongo:latest
        # restart: always
        ports:
            - ${MONGO_PORT}:27017

    neo4j-default:
        image: neo4j:latest
        # restart: always
        environment:
            NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
        ports:
            - ${NEO4J_DEFAULT_PORT}:7687
            # No bolt port because it can't be easily remapped and we would have multiple of them.
        volumes:
            - ./data/inputs:/import:ro

    # Add other Neo4j instances for other databases if needed
    
    neo4j-a:
        image: neo4j:latest
        # restart: always
        environment:
            NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
        ports:
            - ${NEO4J_A_PORT}:7687
            # No bolt port because it can't be easily remapped and we would have multiple of them.
        volumes:
            - ./data/inputs:/import:ro
