name: "aimm"

services:
    postgres:
        image: postgres:latest
        # restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_ROOT_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        expose:
            - 5432

    mongo:
        image: mongo:latest
        # restart: always
        expose:
            - 27017

    neo4j-edbt:
        image: neo4j:latest
        # restart: always
        environment:
            NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
        expose:
            - 7687
        volumes:
            - ./data/inputs/edbt:/import:ro

networks:
    default:
        name: mmcat-network
        external: true
