name: "aimm"

services:
    postgres:
        image: postgres:latest
        # restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432

    mongo:
        image: mongo:latest
        # restart: always
        ports:
            - ${MONGO_PORT}:27017

    neo4j:
        image: neo4j:latest
        # restart: always
        environment:
            NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
        ports:
            - ${NEO4J_PORT}:7687
            # The bolt port has to be as is because the browser client expects it to be there.
            - 7474:7474
        volumes:
            - ./data/inputs:/import:ro
