postgres:
  user: "myuser"
  password: "mypassword"
  host: "localhost"
  port: "5432"
  dbname: "postgres"

mongodb:
  uri: "mongodb://localhost:27017/"
  database: "tpch_mongo"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "password"

# schema_mapping:
#   customer: postgres
#   orders: postgres
#   lineitem: postgres

# schema_mapping:
#   customer: neo4j
#   orders: neo4j
#   lineitem: neo4j

schema_mapping:
  region: postgres
  nation: postgres
  customer: postgres
  orders: postgres
  lineitem: postgres
  part: postgres
  supplier: postgres
  partsupp: postgres


# schema_mapping:
#   customer: neo4j
#   orders: postgres
#   lineitem: mongodb